name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5

    - uses: actions/checkout@v2

    - name: lint markdown
      run: |
        npm install
        npm test

    - name: build site in sn0wcat/builder container
      run: |
        mkdir _site
        docker run \
        -v ${{ github.workspace }}/_data:/srv/jekyll/_data \
        -v ${{ github.workspace }}/docs:/srv/jekyll/docs \
        -v ${{ github.workspace }}/.build:/srv/jekyll/.build \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        sn0wcat/builder:latest \
        bash -c "cd /srv/jekyll && bash .build/build.sh"

    - name: Upload a Build Artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2.2.3
      with:
          path: _site/
          retention-days: 10
  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:

      - uses: actions/download-artifact@v2

      - name: Deploy site to opensource.mindsphere.io
        run: |
          ls -la
          docker run --rm  \
            -v ${{ github.workspace }}/artifact:/root/artifact \
           -e AWS_ACCESS_KEY_ID \
           -e AWS_SECRET_ACCESS_KEY \
           -e AWS_DEFAULT_REGION \
           -e AWS_BUCKET \
           -e AWS_DEPLOYMENT_ID \
           amazon/aws-cli:latest \
           s3 sync --delete /root/artifact/ s3://$AWS_BUCKET/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_DEPLOYMENT_ID: ${{ secrets.AWS_DEPLOYMENT_ID }}

      - name: Invalidate distribution
        run: |
          docker run --rm \
           -e AWS_ACCESS_KEY_ID \
           -e AWS_SECRET_ACCESS_KEY \
           -e AWS_DEFAULT_REGION \
           -e AWS_BUCKET \
           -e AWS_DEPLOYMENT_ID \
           amazon/aws-cli:latest \
           cloudfront create-invalidation --distribution-id $AWS_DEPLOYMENT_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_DEPLOYMENT_ID: ${{ secrets.AWS_DEPLOYMENT_ID }}
